name: demandforge-env
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.13
    - snakemake
    - pandas
    - pyarrow
    - geopandas
    - rasterio
    - xarray
    - numpy
    - polars
    - h5netcdf
    - notebook
    - seaborn
    - pip
    - pip:
          - entsoe-py
          - cdsapi
          - python-dotenv
          - google-cloud-storage
          - platformdirs
