"""Generate docs/flags.md from the scenario-flag registry (single source of truth).

Run from the repo root:  python docs/gen_flags_doc.py
Kept deterministic so the generated table can be committed and diffed. A test
(tests/test_registry.py-adjacent) can assert the row count == len(FLAG_REGISTRY).
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from clever.scenario.registry import BASE_PREFIXES, FLAG_REGISTRY  # noqa: E402

OUT = REPO_ROOT / "docs" / "flags.md"

HEADER = """<!-- GENERATED by docs/gen_flags_doc.py from clever/scenario/registry.py — do not edit by hand. -->
# Scenario-flag vocabulary

A run is fully described by its **scenario string**, e.g.

```
R0_v1_nuke_bioLow_atr_el700_corr2x_noGas_elecX180_h2HIGH_vreEXT_nofloor_noElecFloor_co2150_batt20_pipekm1000
```

It starts with a **base prefix** and is followed by any number of `_`-separated **flag
tokens**, in any order. Validation is *structural* (`clever/scenario/registry.py`): a
string is valid iff every token is a declared flag below — so **adding a lever means
adding one `Flag` to the registry**, nothing else.

**Base prefixes:** {bases}

Each flag's regex is the token *after* the leading `_`. The parser column names the pure
function in `clever/scenario/parse.py` that resolves the value (blank = structural
modifier or base-inherited gate resolved in `clever/overrides.py`).
"""


def _parser_name(fl) -> str:
    p = fl.parser
    return f"`{p.__name__}`" if p is not None else "—"


def main() -> None:
    bases = ", ".join(f"`{b}`" for b in BASE_PREFIXES)
    lines = [HEADER.format(bases=bases), "", "| flag | token regex | kind | changes | parser |", "|---|---|---|---|---|"]
    for fl in FLAG_REGISTRY:
        lines.append(
            f"| `{fl.name}` | `{fl.token}` | {fl.kind} | {fl.changes} | {_parser_name(fl)} |"
        )
    lines.append("")
    lines.append(f"_{len(FLAG_REGISTRY)} flags declared._")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({len(FLAG_REGISTRY)} flags).")


if __name__ == "__main__":
    main()
